# Generated by Django 3.0 on 2020-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=100)),
                ('client_upload', models.FileField(upload_to='')),
                ('file_uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
