# Generated by Django 3.0 on 2020-02-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientupload',
            name='file_uploaded_date',
        ),
    ]
